spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://119.27.176.115:10199/user?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: root
    password: abc123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  redis:
    host: 139.9.113.206
    port: 6379
    jedis:
      pool:
        max-active: -1
        max-wait: 3000ms
    timeout: 3000ms
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  error:
    whitelabel:
      enabled: false
    include-message: always